### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by jangxx** [llealloo/vrc-udon-audio-link#135]
This is a trivial issue, but I noticed that the AudioLink texture contains 2.05 for the version number in 0.2.6, which also matches the version constant in AudioLink.cs:

https://github.com/llealloo/vrc-udon-audio-link/blob/e2a8c0972b973bcec702823dd472583a479b6f9d/AudioLink/Scripts/AudioLink.cs#L26

**Comment by pema99** [comment]
Ah, good catch! Feel free to submit a PR, otherwise I'll probably get to updating this some time after next week.

**Comment by pema99** [comment]
Will be fixed in next release
