### ISSUE TITLE
AVPro problem with low pass filter on audio source

### ISSUE THREAD

**Issue by adamszendrey** [llealloo/vrc-udon-audio-link#156]
Hello!

I've been trying to find information on this problem that I ran into but so far no luck, so I'm hoping it's okay if I open this ticket here.

I'm using unity version 2019.4.31f1, and the latest version of all the stuff involved (as of the writing of this), such as u#, u# player, vrc SDK.

The problem is as follows:
 I want to be able to use audiolink in my world with both regular videos and live streams, from the same audio source, and a single instance of audiolink , without the need to switch things around (beyond the player of course), since that is cumbersome. I've been able to do this, by having the same audio source as the target of the vrc unity video player and be a source for AVpro (adding the avpro speaker component to it). In the world I want to use this however, I'd like to have a low pass filter applied to the source so at a distance the music gets muffled. This works fine in regular video mode, but as soon as I switch to stream mode in the player (u# player), while audio still plays just fine , AudioLink stops receiving audio data seemingly. When I remove the low pass filter component, it works again in stream mode.

Now I do realize that AVpro doesn't care about the filter and it doesn't work for the audio , at least it works for regular videos, but because audiolink stops working when the player is in stream mode , and I don't want to use multiple audio sources and switch around, AND unfortunately the vrc unity video player , while theoretically supporting it, can't output to multiple audio sources (only element0  works), this basically prohibits me from using the low pass filter (since then audiolink wont work in stream mode). It would be nice if audiolink would keep working with AVpro even with the filter component applied to the audio source.

I realize that is a bit long winded and I'm not sure if I explained this well enough...hopefully yes.

Thank you,

Best Regards,

Adam

**Comment by pema99** [comment]
Hello. Do you happen to have a project where you can reproduce that you could share? That might help speed up troubleshooting.

**Comment by adamszendrey** [comment]
Hello! I do but it's fairly sizeable, so I'll probably just create a small project to demonstrate the problem, and post it here (if that's possible - also, haven't checked if there have been any new releases since I wrote my original message). Thanks for your reply!

**Comment by pema99** [comment]
Either posting here or on some file hosting website like google drive works fine.

**Comment by pema99** [comment]
Closing this for now. Please reopen if you are still having issues.
