### ISSUE TITLE
Wrong default transform values "AudioLink" prefab.

### ISSUE THREAD

**Issue by MrDummyNL** [llealloo/vrc-udon-audio-link#157]
If you put prefab "AudioLink" in the Hierarchy instead of scene, it's crazy it has transform coords with extreme values at 
73795, 99824, 92375.

Please, reset the transform part at 0,0,0.
All prefabs should checked at default transform position and rotation. Not such extreme values.

**Comment by llealloo** [comment]
It is by design. For the global texture & concomitant avatar sync to work properly, the quad and camera need to be fully clipped from view. If you place the AudioLink prefab at 0,0,0 where it can be seen, it will break AudioLink.

**Comment by MrDummyNL** [comment]
Whoa. Okay.

**Comment by llealloo** [comment]
I am aware of the yellow warning, that is normal. I will make a note in the setup guide so there are no surprises. You're not wrong for bringing the warning to my attention :)
