### ISSUE TITLE
isInstanceOwner is always 1

### ISSUE THREAD

**Issue by jangxx** [llealloo/vrc-udon-audio-link#161]
For some reason, reading the player info part of the AudioLink texture will always have the `isInstanceOwner` field set to 1. Player count and `isMaster` work as they should, but `isInstanceOwner` doesn't. You can also see this effect on the _AudioLinkQuickView_ material that comes with the Unity package.

**Comment by techanon** [comment]
Issue can be closed. Fixed with above merged PR.
