### ISSUE TITLE
9 System.Exceptions

### ISSUE THREAD

**Issue by Ashe-Void** [llealloo/vrc-udon-audio-link#165]
Unity 2019.4.31f1, AudioLink 0.2.7, UdonSharp 0.20.3

I am a huge newbie when it comes to Udon and Udonsharp. But I followed the install instructions for both AudioLink and UdonSharp, but it throws a few errors when compiling the code.

![image](https://user-images.githubusercontent.com/98918267/156748684-b79481b7-7e62-4b20-b7eb-68c590560134.png)

**Comment by pema99** [comment]
Hey. Are there any other errors in the console, or are we seeing the full picture here?
Are you using the full or minimal release?

These errors are, admittedly, pretty opaque. I'd suggest deleting the 'Library' folder of your project and trying again. Don't do it without a backup, though. If the project isn't gigantic, I might be able to help you better if you zip it up and send it to me.

**Comment by Ashe-Void** [comment]
AudioLink v0.2.7_Full. Project would be very large to send

Reopening project I had tons of System.Exception errors for other UdonSharp scripts I've installed. Trying to recompiled kept failing. After removing AudioLink I was able to compile and had no errors for any of the scripts.

![image](https://user-images.githubusercontent.com/98918267/156763862-1faba2b2-b54d-491e-9f08-867bd3471a7b.png)

**Comment by Ashe-Void** [comment]
Oh wow yeah that's sorted me out, I feel so dumb for missing it. Thank you!

**Comment by pema99** [comment]
No need to apologize, these files probably shouldn't be included in the release. I'll note it down
