### ISSUE TITLE
Change Audiosource at runtime

### ISSUE THREAD

**Issue by SCAbruh** [llealloo/vrc-udon-audio-link#185]
Hello, I've never created a world before so pardon me if this question is stupid:
Is there any way to change the AudioSource used by Audiolink at runtime?

**Comment by pema99** [comment]
https://github.com/llealloo/vrc-udon-audio-link/blob/master/AudioLink/Scripts/AudioLink.cs#L34

The variable controlling the audio source used is public. You should be able to set it from your own script at runtime.
