### ISSUE TITLE
Add " VRC.SDKBase. " BEFORE " Utilities.isValid() " 

### ISSUE THREAD

**Issue by Tiber-Legacy** [llealloo/vrc-udon-audio-link#186]
### Add " VRC.SDKBase. " BEFORE " Utilities.isValid() " 
I'm don't know if this was changed on VRC's end or what but this fixes some 'namespace' errors related to this function on the current SDK.

**Comment by Float3** [comment]
Hi there, are you still experiencing this issue?

**Comment by Float3** [comment]
VRC.SDKBase is included as the first thing in every script we use that method in, so there shouldn't
be a difference.

**Comment by Float3** [comment]
Discussion in #191
