### ISSUE TITLE
AudioReactiveObject scale doesn't work

### ISSUE THREAD

**Issue by llealloo** [llealloo/vrc-udon-audio-link#2]
The AudioReactiveObject scale effector has no effect. The fix has been found and will be in the next release

**Comment by seanidzenga** [comment]
As I was just about to test AudioReactiveObject with a scale effector in my project I was notified of this issue - crazy coincidence.

**Comment by llealloo** [comment]
Sorry I have known about this one for a while, but I have been working full steam ahead on a massive release coming likely some time this week. This issue will be resolved along with that release!

**Comment by seanidzenga** [comment]
No worries, can't wait to see the new release!
