### ISSUE TITLE
Multiple audio links for larger worlds or at least a way to add multiple audio sources?

### ISSUE THREAD

**Issue by aldumgames** [llealloo/vrc-udon-audio-link#205]
I have quite a large world and I have 2 spaces that need audio link for 2 separate players one on an outdoor stage and another for an interior club. just an idea.

**Comment by float3** [comment]
You can change the AudioSource at runtime. Switch when players go from one area to the other. Would that work for you?

**Comment by aldumgames** [comment]
how would i do that

**Comment by float3** [comment]
something like this
```cs
using UdonSharp;
using UnityEngine;
using VRCAudioLink;

public class AudioSourceSwitch : UdonSharpBehaviour
{
    [SerializeField] public AudioLink audioLink;
    [SerializeField] public AudioSource[] AudioSources;

    void SwitchAudioSource()
    {
        if (audioLink.audioSource == AudioSources[0])
        {
            audioLink.audioSource = AudioSources[1];
        }
        else
        {
            audioLink.audioSource = AudioSources[0];
        }
    }
}
```

**Comment by float3** [comment]
Now make a collider and on player collision call the SwitchAudioSource method

**Comment by float3** [comment]
https://docs.vrchat.com/docs/player-collisions

**Comment by aldumgames** [comment]
this method is proving more difficult because of the layout, the world has teleport points to different areas and find your friends so i don't know how to set it up so its easy for someone to bypass the collider

**Comment by aldumgames** [comment]
i also have no idea how to tell it to call the script

**Comment by float3** [comment]
In that case, it's even simpler since you can build the audio source switch right into the teleport system

**Comment by float3** [comment]
I can help you with implementing that; it should be pretty straightforward.

Are you willing to join the AudioLink discord?

**Comment by aldumgames** [comment]
yeah sure

**Comment by aldumgames** [comment]
i have joined
