### ISSUE TITLE
pi Aurora Failed to import (got any ideas or is this Pi's issue?)

### ISSUE THREAD

**Issue by Llamahat** [llealloo/vrc-udon-audio-link#217]
Shader error in '_pi_/Aurora': failed to open source file: '../../AudioLink/Shaders/AudioLink.cginc' at line 49 (on d3d11)

Compiling Fragment program with GEOM_TYPE_MESH
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by float3** [comment]
This is because we changed the location of our cginc. So pi would have to update it.

BUT:
We include a tool that will allow you to update include paths automatically check the menuitem under Audiolink that says something with upgrade
