### ISSUE TITLE
How to install on an OS other then Windows using VCC?

### ISSUE THREAD

**Issue by AftDawn** [llealloo/vrc-udon-audio-link#227]
Hi, i use linux to make my avatars and i can't install VCC nor can i get the command line utility to work, how would one go about installing this then?

Would it have something to do with the unitypackage in releases?

**Comment by pema99** [comment]
The unity package contains the same content as the regular package release. If you want use Audiolink without VCC or VPM, you can use that. 

If this is for an avatar project, that's all you need, but for worlds, you also need to get UdonSharp 1.x (earlier versions won't work). 

UdonSharp 1.x is currently only officially distributed by VRChat via the VPM/VCC as they are pushing for this to be the only supported method of obtaining packages. You can grab UdonSharp 1.x off of VRChat's CDN with a bit of know how, but I'm not sure I should be posting direct links here.

Alternatively you can use this template project which contains a package resolver that will pull in UdonSharp https://github.com/vrchat-community/template-udonsharp

**Comment by AftDawn** [comment]
Ok, i did that and it's in now, i do still have problems but i'm gonna make another issue for that.
