### ISSUE TITLE
"AudioLinkAvatar needs upgrade on source prefab asset" and "Script does not belong to a U# assembly"

### ISSUE THREAD

**Issue by AftDawn** [llealloo/vrc-udon-audio-link#228]
(Continuation from #227)
Hi, i'm getting alot of errors in my console and my avatar (not making worlds, just an avatar) is invisible whenever i drag in the `AudioLinkAvatar` prefab, is it cause of UdonSharp doing something to the prefab?

![image](https://user-images.githubusercontent.com/42480566/220515409-fb8d891a-3846-474d-816f-187612fa69b3.png)

**Comment by float3** [comment]
You shouldn't have UdonSharp in your Avatar project

**Comment by AftDawn** [comment]
Ok, so i've removed UdonSharp and the VRC World SDK, but that doesn't remove any of the issues, avatar is still invis, but now there's missing scripts
![image](https://user-images.githubusercontent.com/42480566/220520303-bc611d95-2a8f-400f-99b6-994a5990263c.png)

**Comment by float3** [comment]
You have to remove the define as well https://github.com/llealloo/vrc-udon-audio-link/blob/dev/FAQ.md#answer-7

**Comment by AftDawn** [comment]
ok, so, i remade the project so that i was working with a clean slate and got the VCC CLI working, i've installed the avatar base and the audio link package into the project, same stuff in the editor: invisible avatar when not in play mode, no music playing, errors in the console, correct Scripting Define Symbols (i don't have UdonSharp in their, but i'm guessing that that's fine cause not making worlds) and no actual audio link using poiyomi toon v8.1.161

**Comment by float3** [comment]
What errors?

Btw no idea what the invisible avatar is about, that's probably nothing to do with audiolink.

**Comment by AftDawn** [comment]
![image](https://user-images.githubusercontent.com/42480566/220863784-4e8bbf00-2a9a-46fe-9737-e37c3b993738.png)

**Comment by float3** [comment]
You can ignore those

**Comment by AftDawn** [comment]
Ok, what about that missing script in the inspection panel? What's that normally?

**Comment by pema99** [comment]
It's a hidden extra component that UdonSharp adds to any GameObject with UdonSharp behavior. The prefab is made this way because code is shared between the avatar and world version of AudioLink. You can ignore it, it's harmless. Feel free to remove the script reference.

**Comment by pema99** [comment]
It's usually hidden but since you don't have U# installed it shows up.

**Comment by pema99** [comment]
If you want to sanity check whether audiolink is working, I suggest just making a new scene, adding the audiolink prefab, adding a cube, and putting the Debug material on the cube (Packages/com.llealloo.audiolink/Runtime/Materials/mat_AudioLinkDebug.mat)

**Comment by AftDawn** [comment]
I'll do that next time I'm at my computer, see if it's poiyomi or audio link

(Fyi, I am on linux, so if audio link doesn't work correctly or whatever, then oh well)

**Comment by pema99** [comment]
Should work fine on Linux. One of our main Contributors uses Linux

**Comment by float3** [comment]
Latest release works just fine on Linux
