### ISSUE TITLE
Ability to select avatar sound as input data

### ISSUE THREAD

**Issue by kenthinson** [llealloo/vrc-udon-audio-link#240]
**Feature Description:**
It would be cool if you could choose to use avatar sounds for input instead of just world sound. 

**Additional context:**
Example if you are making a avatar with a song animation this would be very cool to use.

**Comment by float3** [comment]
This is currently impossible.

We should add this to the faq

**Comment by float3** [comment]
I should have added that this isn't something we can implement, it would have be on vrc's side
