### ISSUE TITLE
"'Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs' does not belong to a U# assembly, have you made a U# assembly definition for the assembly the script is a part of?"

### ISSUE THREAD

**Issue by VeryCuriousToy** [llealloo/vrc-udon-audio-link#262]
Hi

I am getting a whole stream of console errors - ... does not belong to U# assembly.

Clicked "Reload SDK" under "VRChat SDK" menu, but does not resolve issue. Using Creator Companion.

Cant find '.asmdef' files, solution outlined here: 
[https://udonsharp.docs.vrchat.com/migration/#does-not-belong-to-u-assembly](https://udonsharp.docs.vrchat.com/migration/#does-not-belong-to-u-assembly)

Thanks

**Comment by pema99** [comment]
Which scripts are you getting the error for?

**Comment by VeryCuriousToy** [comment]
Hi @pema99 

All of the cs scripts in the AudioLink/Runtime/Scripts folder - AudioLink.cs, AudioLinkController.cs etc

They all have their own respective log eg:

[UdonSharp] Script 'Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs' does not belong to a U# assembly, have you made a U# assembly definition for the assembly the script is a part of?
UnityEngine.Debug:LogError (object,UnityEngine.Object)
UdonSharp.UdonSharpUtils:LogError (object,UnityEngine.Object) (at Packages/com.vrchat.udonsharp/Editor/UdonSharpUtils.cs:329)
UdonSharp.Compiler.UdonSharpCompilerV1:ValidateUdonSharpBehaviours (UdonSharp.UdonSharpProgramAsset[],System.Collections.Generic.HashSet`1<string>) (at Packages/com.vrchat.udonsharp/Editor/Compiler/UdonSharpCompilerV1.cs:392)
UdonSharp.Compiler.UdonSharpCompilerV1:Compile (UdonSharp.Compiler.UdonSharpCompileOptions) (at Packages/com.vrchat.udonsharp/Editor/Compiler/UdonSharpCompilerV1.cs:323)
UdonSharp.UdonSharpProgramAsset:CompileAllCsPrograms (bool,bool) (at Packages/com.vrchat.udonsharp/Editor/UdonSharpProgramAsset.cs:295)
UdonSharpEditor.UdonSharpEditorUtility:UpgradeSceneBehaviours (System.Collections.Generic.IEnumerable`1<VRC.Udon.UdonBehaviour>) (at Packages/com.vrchat.udonsharp/Editor/UdonSharpEditorUtility.cs:650)
UdonSharpEditor.UdonSharpEditorManager:RunAllUpgrades () (at Packages/com.vrchat.udonsharp/Editor/UdonSharpEditorManager.cs:1618)
UdonSharpEditor.UdonSharpEditorManager:RunPostAssemblyBuildRefresh () (at Packages/com.vrchat.udonsharp/Editor/UdonSharpEditorManager.cs:123)
UnityEditor.AssemblyReloadEvents:OnAfterAssemblyReload ()

**Comment by float3** [comment]
you could try selecting the following files and selecting reimport from the the right click context menu:

AudioLink.USharp.asset
AudioLink.USharp.asset.meta
AudioLink.asmdef
AudioLink.asmdef.meta

**Comment by pema99** [comment]
Closed due to inactivity.
