### ISSUE TITLE
Audiolink give me errors with UdonSharp on import

### ISSUE THREAD

**Issue by GatzeGalaxy** [llealloo/vrc-udon-audio-link#264]
I have a problem when im try to use AudioLink in my project, for some reason when I import the AudioLink package UdonSharp give me errors, this is the first:

![error1](https://github.com/llealloo/vrc-udon-audio-link/assets/103001791/5c572b4c-5b5e-4800-888c-1a032b66749d)

Later I add the Audiolink Prefab to my scene, and when I open it to configure, give me this another error:

![error2](https://github.com/llealloo/vrc-udon-audio-link/assets/103001791/42fcbd88-df73-4ba8-b23b-3591c200747d)

I tried deleting the Udon Behaviour and put it again, and when im going to put the AudioLink im his space my Unity crash intannely...
And obviously it won't let me upload the map to vrchat...

Im using Unity 2019.4.31f1, with VRChat Creator Companion, with the last update of everything, UdonSharp, Audiolink...
I tryed everything and read the frequent questions a lot of times and nothing work, any idea what could be wrong?

Thanks

**Comment by float3** [comment]
try this step https://github.com/llealloo/vrc-udon-audio-link/blob/master/FAQ.md#answer-7

**Comment by pema99** [comment]
Closed due to inactivity. Let us know if you are still facing issues.
