### ISSUE TITLE
Audiolink running error

### ISSUE THREAD

**Issue by KigerUCM** [llealloo/vrc-udon-audio-link#265]
**Describe the bug in detail:**
Packages\com.llealloo.audiolink\Editor\Scripts\AudioLinkAssetManager.cs(9,11): error CS0234: The type or namespace name 'PackageManagement' does not exist in the namespace 'VRC' (are you missing an assembly reference?)
Packages\com.llealloo.audiolink\Editor\Scripts\AudioLinkAssetManager.cs(10,11): error CS0234: The type or namespace name 'PackageManagement' does not exist in the namespace 'VRC' (are you missing an assembly reference?)

**Provide steps/code to reproduce the bug:**
Updating VRChat SDK- Worlds 3.2.1 with UdonSharp 1.1.8 using VCC installation will activate this error

**Expected behavior:**
Works fine

**Additional Information:**
Provide any additional information here.

**Comment by teehzero** [comment]
It's not clear what problem this is causing. Can you describe how it behaves differently than you expect in more detail?

**Comment by float3** [comment]
are you sure you installed the base sdk?

**Comment by pema99** [comment]
Closed due to inactivity. Let us know if you are still facing issues.
