### ISSUE TITLE
AudioLink 0.3.2 error when importing.

### ISSUE THREAD

**Issue by HamNCheeseBorger** [llealloo/vrc-udon-audio-link#276]
**Describe the bug in detail:**
I get an error when importing AudioLink to my VRChat project. It is an avatar project. 
Here is the error in question:

Packages\com.llealloo.audiolink\Editor\Scripts\AudioLinkAssetManager.cs(9,11): error CS0234: The type or namespace name 'PackageManagement' does not exist in the namespace 'VRC' (are you missing an assembly reference?)

Packages\com.llealloo.audiolink\Editor\Scripts\AudioLinkAssetManager.cs(10,11): error CS0234: The type or namespace name 'PackageManagement' does not exist in the namespace 'VRC' (are you missing an assembly reference?)

**Provide steps/code to reproduce the bug:**
Import VRCSDK using CreatorCompanion. 
Import AudioLink after importing other essential packages my project needs. 
I get error.

**Expected behavior:**
Idk, for it to work?

**Additional Information:**
This is on an already started project i have been working on for 2 days now. Yes my SDK is the latest version. Yes the Unity version is the appropriate version. Yes I am using the CreatorCompanion to install this stuff. I am not new to avatar making but I am to audiolink and i wanted to experiment with it to get to understand it.
Version of AudioLink I am importing is 0.3.2

**Comment by float3** [comment]
@pema99 any ideas?

**Comment by float3** [comment]
@HamNCheeseBorger have you tried using the "Reload SDK" feature?

**Comment by pema99** [comment]
It sounds like the package resolver is missing. That isn't supposed to happen. New projects created via VCC get it by default, and migrated projects get it added during migration

**Comment by pema99** [comment]
You can try using the VCC to manually add the package resolver https://vcc.docs.vrchat.com/vpm/resolver/

**Comment by pema99** [comment]
We're gonna get rid of the package resolver dependency in next release, which will solve this. Closing.
