### ISSUE TITLE
Please Document the VPM Install Method

### ISSUE THREAD

**Issue by owlboy** [llealloo/vrc-udon-audio-link#278]
**Feature Description:**
Please document the install method for those who use the CLI / VPM.

`vpm add package com.llealloo.audiolink`

**Additional context:**
Not everyone develops on Windows! Thanks!

**Comment by float3** [comment]
you can make a pr

**Comment by owlboy** [comment]
The reason I'm looking for the docs on this is for an authoritative answer. I'm not the authority. 😅

**Comment by pema99** [comment]
Sorry never gotten around to this since I've never used the vpm CLI myself

**Comment by float3** [comment]
> Sorry never gotten around to this since I've never used the vpm CLI myself

I'll write it

**Comment by float3** [comment]
https://github.com/llealloo/vrc-udon-audio-link/tree/cli-instructions?tab=readme-ov-file#linuxmacoswindows

@owlboy here's my draft, If you wish to give feedback

**Comment by float3** [comment]
merged in https://github.com/llealloo/vrc-udon-audio-link/pull/297
