### ISSUE TITLE
Theme Colors and Mode Revert to Default at Runtime

### ISSUE THREAD

**Issue by Saberpeep** [llealloo/vrc-udon-audio-link#281]
**Describe the bug in detail:**
Any custom values for AudioLink theme colors and theme mode dropdown revert to defaults at runtime.

**Provide steps/code to reproduce the bug:**
1. Add AudioLink prefab and controller prefab to your scene.
2. Change theme colors and/or mode in the inspector on the AudioLink script.
3. Either build and test or enter play mode with ClientSim.
4. Observe that the mode dropdown has been set back to ColorChord, and the theme colors have reverted to the default yellow, blue, red, green.

**Expected behavior:**
The theme colors and mode should retain the values set in the inspector before entering play mode.

**Additional Information:**
Tested with release 0.3.2
~~I was going to make a pull request; but in fixing it I managed to break sync for late joiners and I'm not well versed enough in U# networking to fix it myself. So I decided to just make an issue report instead.~~

**Comment by pema99** [comment]
Fixed here https://github.com/llealloo/vrc-udon-audio-link/commit/d16349dca4c387c03a624f206c63ac9d23b8e333
