### ISSUE TITLE
Leave world creates an avoidable log error

### ISSUE THREAD

**Issue by Ess-Ka** [llealloo/vrc-udon-audio-link#283]
When the player leaves a world with AudioLink 0.3.2, an error will be throwed and this is visible in the log. A null or IsValid check is missing on the playerApi object (AudioLinks.cs:338).

Log:
```
2023.09.23 16:14:04 Error      -  [UdonBehaviour] An exception occurred during Udon execution, this UdonBehaviour will be halted.
VRC.Udon.VM.UdonVMException: The VM encountered an error!
Exception Message:
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__get_isInstanceOwner__SystemBoolean'.
      Parameter Addresses: 0x000000EA, 0x000000EB
  
  Object reference not set to an instance of an object.
```

**Comment by pema99** [comment]
Should be fixed in next release https://github.com/llealloo/vrc-udon-audio-link/commit/8ea997e67abbdc9ed27f7d1b219de55e9d402e64
